export const queryKeys = {
  feed: (params) => ['feed', params],
  post: (id) => ['posts', id],
  postComments: (id) => ['posts', id, 'comments'],
  communities: (params) => ['communities', 'list', params],
  community: (name) => ['communities', 'detail', name],
  communityPosts: (name, params) => ['communities', 'detail', name, 'posts', params],
  communityMembers: (name, params) => ['communities', 'detail', name, 'members', params],
  me: ['users', 'me'],
  user: (username) => ['users', username],
  userPosts: (username, params) => ['users', username, 'posts', params],
  userComments: (username, params) => ['users', username, 'comments', params],
  search: (params) => ['search', params],
  adminCommunityActivity: (name, params) => ['admin', 'communities', name, params],
  adminUserActivity: (username, params) => ['admin', 'users', username, params],
  adminTopActive: (params) => ['admin', 'top-active', params],
  auditLogs: (params) => ['audit-logs', params],
  communityAutocomplete: (q) => ['communities', 'autocomplete', q],
};
